server:
  port: 1111
spring:
  application:
    name: erueka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    hostname: localhost