server:
  port: 9800
spring:
  application:
    name: hello-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
logbook:
  write:
    level: info
  format:
    style: http