server:
  port: 8080
spring:
  application:
    name: spring-boot-text-transform
  freemarker:
    suffix: .ftl
    allow-request-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-spring-macro-helpers: false
    expose-session-attributes: false
    expose-request-attributes: false